// Offizielle AfA-Tabelle des Bundesfinanzministeriums (Auszug für gängige Wirtschaftsgüter)
const AFA_DATABASE = [
    { name: "Personalcomputer (PC), Desktop-PCs, Workstations", years: 1, source: "BMF-Schreiben vom 26.02.2021 (Sofortabschreibung digitaler Wirtschaftsgüter)" },
    { name: "Notebooks, Laptops, Tablets, Convertibles", years: 1, source: "BMF-Schreiben vom 26.02.2021 (Sofortabschreibung digitaler Wirtschaftsgüter)" },
    { name: "Monitore, Displays, Beamer", years: 1, source: "BMF-Schreiben vom 26.02.2021" },
    { name: "Drucker, Scanner, All-in-One-Geräte", years: 1, source: "BMF-Schreiben vom 26.02.2021" },
    { name: "Anwendungssoftware, ERP-Software, Betriebssysteme, Office-Lizenzen", years: 1, source: "BMF-Schreiben vom 26.02.2021" },
    { name: "Mobiltelefone, Smartphones", years: 3, source: "AfA-Tabelle AV - Pos. 6.13.1" },
    { name: "Büromöbel (Bürostuhl, Schreibtisch, Aktenschrank, Regale, Konferenztisch)", years: 13, source: "AfA-Tabelle AV - Pos. 6.2" },
    { name: "Personenkraftwagen (PKW) - Neufahrzeuge", years: 6, source: "AfA-Tabelle AV - Pos. 5.1" },
    { name: "Elektro-Fahrräder, E-Bikes, Pedelecs (Kanzlei-Leasing)", years: 7, source: "AfA-Tabelle AV - Pos. 5.7" },
    { name: "Drohnen, Quadrocopter (z.B. für Immobilienfotos, Dokumentation)", years: 5, source: "AfA-Tabelle AV - Pos. 5.6 (Luftfahrzeuge / Kleingeräte)" },
    { name: "Fotokamera, Spiegelreflexkamera, Videokamera (Fotoapparate)", years: 7, source: "AfA-Tabelle AV - Pos. 6.11" },
    { name: "Kopiergeräte (Fotokopierer, Hochleistungskopierer)", years: 7, source: "AfA-Tabelle AV - Pos. 6.5.2" },
    { name: "Aktenvernichter, Schredder", years: 8, source: "AfA-Tabelle AV - Pos. 6.6.3" },
    { name: "Klimageräte (mobil)", years: 10, source: "AfA-Tabelle AV - Pos. 6.15" },
    { name: "Geldtresor, Safe, Wertschutzschrank", years: 15, source: "AfA-Tabelle AV - Pos. 6.8" },
    { name: "Kaffeemaschine, Kaffeevollautomat (Kanzleiküche)", years: 5, source: "AfA-Tabelle AV - Pos. 6.13" },
    { name: "Geschirrspüler, Kühlschrank (Kanzleiküche)", years: 10, source: "AfA-Tabelle AV - Pos. 6.14" },
    { name: "Lastkraftwagen (LKW) bis 3,5t", years: 6, source: "AfA-Tabelle AV - Pos. 5.2.1" },
    { name: "Lastkraftwagen (LKW) über 3,5t", years: 9, source: "AfA-Tabelle AV - Pos. 5.2.2" },
    { name: "Elektro-Ladestation, Wallbox (für PKW)", years: 10, source: "AfA-Tabelle AV - Pos. 3.4.5" },
    { name: "Telefonanlage, Telefon-Endgeräte (Festnetz)", years: 8, source: "AfA-Tabelle AV - Pos. 6.13.2" },
    { name: "Server-Hardware, Netzwerkschränke, Router, Switches", years: 1, source: "BMF-Schreiben vom 26.02.2021" },
    { name: "Teppichböden, Auslegeware (Kanzleiräume)", years: 8, source: "B FH-Rechtsprechung" },
    { name: "Beleuchtungsanlagen, Lampen, Leuchten", years: 15, source: "AfA-Tabelle AV - Pos. 3.1.4" },
    { name: "Kombikraftwagen, SUV, Vans", years: 6, source: "AfA-Tabelle AV - Pos. 5.1" },
    { name: "Motorrad, Roller (Zweiräder)", years: 7, source: "AfA-Tabelle AV - Pos. 5.5" },
    { name: "Lagerregale (Schwerlast)", years: 14, source: "AfA-Tabelle AV - Pos. 3.3.4" },
    { name: "Werkzeuge (Handwerkszeug)", years: 5, source: "AfA-Tabelle AV - Pos. 3.6" }
];
